### ISSUE TITLE
PSNR, SSIM and LPIPS

### ISSUE THREAD

**Issue by ChchNiu** [changzheng123/L-CoDe#2]
Hello!
Thank you for your excellent work. The paper shows the numerical results of PSNR, SSIM and LPIPS, but the project does not provide a procedure for calculating the indicators. Can you provide a procedure for evaluating the indicators？
Thank you for your help, and waiting for your answer.

**Comment by utoper23** [comment]
I also appreciate your excellent work. I have the same problem. Although we calculated SSIM and PSNR through "skimage.metrics", the reproduced results were quite different. Could you please provide the code of your evaluation index measurement and val folder so that we could also measure the similar performance (24.965 91.657% 0.169)?

**Comment by changzheng123** [comment]
Thanks for following our work! We test PSNR and SSIM with functions from the sklearn library. Since the predictions are transformed from LAB to RGB, we do the same for GT.
```python
ground_truth = np.array(Image.open(ground_truth_path).resize((cfg.TRAIN.HEIGHT, cfg.TRAIN.WIDTH), Image.BILINEAR))
ground_truth_lab = cv2.cvtColor(ground_truth, cv2.COLOR_RGB2Lab)
ground_truth = cv2.cvtColor(ground_truth_lab, cv2.COLOR_Lab2RGB)

predicted_path = os.path.join(predicted_dir, img)
predicted = np.array(Image.open(predicted_path))
psnr = compare_psnr(ground_truth, predicted, 255)
ssim = compare_ssim(ground_truth, predicted, data_range=255, multichannel=True)

ground_truth = img2tensor(ground_truth)
predicted = img2tensor(predicted)
lpips_vgg =lpips.LPIPS(net='vgg')(ground_truth,predicted)
```
